#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_pyside_launcher_android.py — PySide 1 / Python 2.6 → Android APK builder

This is a FUNDAMENTALLY DIFFERENT approach from build_pyside_android.py.
Instead of compiling Shiboken/PySide/Qt from source (which has been bit-
rotting for 13 years), we use three PREBUILT artifacts published by the
PySide-for-Android project:

    1. PySideLauncher-debug.apk         — A signed APK that loads
                                          any PySide app from its
                                          assets/ folder at runtime.
    2. data_python.tgz                  — Python 2.6 runtime for ARM
                                          + compiled PySide 1 bindings.
    3. data_data_eu.licentia...qt.tgz   — Qt 4 libraries for ARM,
                                          targeting API-8 platform.

Build pipeline:

    Step 1  Preflight   — verify the user's project layout (main.py)
    Step 2  Workspace   — set up tmp dirs, download apktool
    Step 3  Download    — fetch the 3 artifacts (with mirror fallback)
    Step 4  Bundle      — zip the user's project as python_project.zip
    Step 5  Decode APK  — apktool d (extract resources, decode manifest)
    Step 6  Inject      — copy python_project.zip into assets/
                          (and the two tarballs if not already present)
    Step 7  Re-package  — optionally rename package + app label
    Step 8  Rebuild APK — apktool b
    Step 9  Zipalign    — required for Android runtime
    Step 10 Sign        — debug-keystore signing (apksigner / jarsigner)
    Step 11 Output      — copy final APK to user's --output-path

The whole thing runs on the GHA runner directly (no Docker needed) and
typically completes in 2-3 minutes.  Cold-cache it's about 5 min total
including downloads.

REQUIREMENTS on host:
  * Python 3.7+
  * java   (any JDK 8+, for apktool / jarsigner / keytool)
  * curl   (for downloads)
  * unzip  (usually preinstalled; for APK inspection)

Apktool, debug.keystore, and zipalign are downloaded / generated by this
script — no system install needed.
"""

from __future__ import print_function
import argparse
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

# ------------------------------------------------------------------ constants

BUILDER_VERSION = 1

# Apktool — single JAR, fetched from official GitHub releases.  This
# version is pinned; bump only if a newer one is needed.
APKTOOL_VERSION = '2.9.3'
APKTOOL_URL = (
    'https://github.com/iBotPeaches/Apktool/releases/download/'
    'v{v}/apktool_{v}.jar'.format(v=APKTOOL_VERSION)
)

# --- Source artifact URL lists.  We try each in order until one works. ---

PYSIDE_LAUNCHER_APK_URLS = [
    'https://archive.org/download/pyside-for-android/PySideLauncher-debug.apk',
    'https://www.dropbox.com/scl/fi/cqna41a6jso3js10tzye8/PySideLauncher-debug.apk?rlkey=dng8p0f9a8blug1znwa89o0a2&st=w74p4n3q&dl=1',
    'https://zenodo.org/records/20370108/files/PySideLauncher-debug.apk?download=1',
]

QT_TARBALL_URLS = [
    'https://archive.org/download/pyside-for-android/data_data_eu.licentia.necessitas.ministro_files_qt.tgz',
    'https://www.dropbox.com/scl/fi/jpckvivl54bmz5kodyj6n/data_data_eu.licentia.necessitas.ministro_files_qt.tgz?rlkey=y3gf2dxnt72rmnlwhyn6dakns&st=rvsp53tp&dl=1',
    'https://zenodo.org/records/20370108/files/data_data_eu.licentia.necessitas.ministro_files_qt.tgz?download=1',
]

PYTHON_TARBALL_URLS = [
    'https://archive.org/download/pyside-for-android/data_python.tgz',
    'https://www.dropbox.com/scl/fi/oix4qkb5ea357eehwl89x/data_python.tgz?rlkey=yg3i0truprihj7k9fbf6vkghq&st=7b2skrzn&dl=1',
    'https://zenodo.org/records/20370108/files/data_python.tgz?download=1',
]

# Sizes used as sanity floors when validating downloads.  Real files are
# ~14-15 MB each for tarballs, the APK is at least ~5 MB.  Anything
# below these floors is almost certainly an HTML error page.
MIN_TARBALL_BYTES = 5 * 1024 * 1024
MIN_APK_BYTES     = 1 * 1024 * 1024
MIN_APKTOOL_BYTES = 1 * 1024 * 1024

# Inside the rebuilt APK, the user's project will live at:
ASSET_PYTHON_PROJECT     = 'python_project.zip'
ASSET_PYTHON_TARBALL     = 'data_python.tgz'
ASSET_QT_TARBALL         = 'data_data_eu.licentia.necessitas.ministro_files_qt.tgz'

log = logging.getLogger('pyside-launcher-builder')


# ------------------------------------------------------------------ helpers

def run(cmd, check=True, cwd=None, env=None, capture=False):
    """Print + run a subprocess command, returning the process result."""
    cmd_str = ' '.join(map(str, cmd))
    log.info('$ %s', cmd_str)
    try:
        result = subprocess.run(
            [str(c) for c in cmd],
            check=check,
            cwd=cwd,
            env=env,
            stdout=subprocess.PIPE if capture else None,
            stderr=subprocess.STDOUT if capture else None,
        )
        if capture:
            return result.stdout.decode('utf-8', 'replace')
        return result.returncode
    except subprocess.CalledProcessError as e:
        log.error('  ! command failed (exit %d): %s', e.returncode, cmd_str)
        raise


def download_with_fallback(urls, dest, min_bytes, label):
    """Try each URL in `urls` until one downloads successfully.

    Validates the downloaded file is at least `min_bytes` (rejects HTML
    error pages and short partial transfers).  Returns the destination
    path on success, raises SystemExit if all URLs fail.
    """
    dest = Path(dest)
    if dest.exists() and dest.stat().st_size >= min_bytes:
        log.info('  ✓ %s already cached: %s (%s)',
                 label, dest, _human_size(dest.stat().st_size))
        return dest

    dest.parent.mkdir(parents=True, exist_ok=True)
    for i, url in enumerate(urls, 1):
        log.info('  [%d/%d] %s', i, len(urls), url)
        if dest.exists():
            dest.unlink()
        try:
            run(['curl', '-L', '--fail', '--retry', '3', '--retry-delay', '5',
                 '--max-time', '600', '-A', 'Mozilla/5.0',
                 '-o', str(dest), url],
                check=False)
        except FileNotFoundError:
            raise SystemExit('  X curl is required but not installed.')
        if dest.exists() and dest.stat().st_size >= min_bytes:
            log.info('    ✓ downloaded %s (%s)',
                     dest.name, _human_size(dest.stat().st_size))
            return dest
        size = dest.stat().st_size if dest.exists() else 0
        log.warning('    ! got %d bytes (need >= %d), trying next mirror',
                    size, min_bytes)
    raise SystemExit(
        '  X all mirrors failed for {label}.\n'
        '    Tried:\n      {urls}\n'
        '    Workaround: download manually and place at {dest}'.format(
            label=label, urls='\n      '.join(urls), dest=dest))


def _human_size(n):
    """Format byte count as MB/KB."""
    if n >= 1024 * 1024:
        return '{:.1f} MB'.format(n / (1024.0 * 1024.0))
    if n >= 1024:
        return '{:.1f} KB'.format(n / 1024.0)
    return '%d bytes' % n


def java_available():
    """Check whether `java` is on PATH and runnable."""
    try:
        out = subprocess.run(['java', '-version'],
                             stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT)
        return out.returncode == 0
    except (FileNotFoundError, OSError):
        return False


def find_tool(name):
    """Locate a tool on PATH or return None."""
    from shutil import which
    return which(name)


# ------------------------------------------------------------------ steps

def preflight(args):
    """Step 1: verify the user's project and required tools."""
    log.info('Step 1/11 -- Preflight')
    log.info('  BUILDER_VERSION  = %d', BUILDER_VERSION)

    project_dir = Path(args.project_dir).resolve()
    if not project_dir.is_dir():
        raise SystemExit('  X project-dir does not exist: %s' % project_dir)

    main_py = project_dir / 'main.py'
    if not main_py.is_file():
        raise SystemExit(
            '  X no main.py at %s\n'
            '    The user project must contain a main.py at its root.' % main_py)

    # Sanity check: ensure main.py uses `from PySide ...` (not PySide2/6 or PyQt)
    src = main_py.read_bytes()
    forbidden_re = re.compile(
        br'^\s*(?:from|import)\s+(PySide2|PySide6|PyQt5|PyQt6)\b',
        re.MULTILINE)
    m = forbidden_re.search(src)
    if m:
        line_num = src[:m.start()].count(b'\n') + 1
        line_start = src.rfind(b'\n', 0, m.start()) + 1
        line_end = src.find(b'\n', m.start())
        if line_end == -1:
            line_end = len(src)
        line = src[line_start:line_end].decode('utf-8', 'replace').rstrip()
        raise SystemExit(
            '  X main.py imports from PySide2/PySide6/PyQt5/PyQt6.\n'
            '    This builder targets PySide 1 + Python 2.6 on Android.\n'
            '    Offending line %d: %s' % (line_num, line))

    pyside1_re = re.compile(
        br'^\s*(?:from|import)\s+PySide(?!\d)\b',
        re.MULTILINE)
    if not pyside1_re.search(src):
        log.warning(
            '  ! main.py does not import PySide (Qt 4) — make sure your\n'
            '    app actually uses PySide 1 bindings.')

    # Java
    if not java_available():
        raise SystemExit(
            '  X java is required for apktool but not found on PATH.\n'
            '    Install with: sudo apt-get install -y openjdk-17-jdk-headless')

    args.project_dir = project_dir
    log.info('  ✓ project_dir   : %s', project_dir)
    log.info('  ✓ main.py       : %s (%d bytes)', main_py, main_py.stat().st_size)
    log.info('  ✓ java          : %s', find_tool('java'))
    log.info('  ✓ curl          : %s', find_tool('curl'))
    log.info('  ✓ unzip         : %s', find_tool('unzip'))


def workspace_setup(args):
    """Step 2: create tmp working dirs and download apktool."""
    log.info('Step 2/11 -- Workspace setup')

    workspace = Path(args.workspace).resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    args.workspace = workspace
    log.info('  ✓ workspace     : %s', workspace)

    # Download apktool jar (small, ~25 MB, cached across runs)
    apktool_jar = workspace / 'apktool.jar'
    if not apktool_jar.exists() or apktool_jar.stat().st_size < MIN_APKTOOL_BYTES:
        log.info('  downloading apktool %s', APKTOOL_VERSION)
        download_with_fallback(
            [APKTOOL_URL], apktool_jar, MIN_APKTOOL_BYTES, 'apktool')
    else:
        log.info('  ✓ apktool       : cached at %s', apktool_jar)
    args.apktool_jar = apktool_jar


def download_artifacts(args):
    """Step 3: fetch the three prebuilt PySide-for-Android artifacts."""
    log.info('Step 3/11 -- Download prebuilt artifacts')

    cache = args.workspace / 'downloads'
    cache.mkdir(parents=True, exist_ok=True)

    args.launcher_apk = download_with_fallback(
        PYSIDE_LAUNCHER_APK_URLS,
        cache / 'PySideLauncher.apk',
        MIN_APK_BYTES, 'PySideLauncher.apk')

    args.qt_tarball = download_with_fallback(
        QT_TARBALL_URLS,
        cache / ASSET_QT_TARBALL,
        MIN_TARBALL_BYTES, 'Qt tarball')

    args.python_tarball = download_with_fallback(
        PYTHON_TARBALL_URLS,
        cache / ASSET_PYTHON_TARBALL,
        MIN_TARBALL_BYTES, 'Python tarball')


def bundle_user_project(args):
    """Step 4: zip the user's project as python_project.zip.

    Layout inside the zip mirrors the project dir, with main.py at the
    top.  We include .py files, common data extensions, and the contents
    of any data/ subdirectory.  Skips __pycache__, *.pyc, .git, .svn,
    and other VCS / editor cruft.
    """
    log.info('Step 4/11 -- Bundle user project as python_project.zip')

    out_zip = args.workspace / 'python_project.zip'
    if out_zip.exists():
        out_zip.unlink()

    excluded_dir_names = {'__pycache__', '.git', '.svn', '.hg', '.idea',
                          '.vscode', '.mypy_cache', '.pytest_cache',
                          'node_modules', '.tox'}
    excluded_suffixes = {'.pyc', '.pyo', '.swp', '.swo', '.bak', '.tmp', '.orig'}

    included = 0
    total_bytes = 0
    with zipfile.ZipFile(str(out_zip), 'w', zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(str(args.project_dir)):
            # In-place prune of dirs to exclude
            dirs[:] = [d for d in dirs if d not in excluded_dir_names
                       and not d.startswith('.')]
            for fname in files:
                if any(fname.endswith(s) for s in excluded_suffixes):
                    continue
                if fname.startswith('.'):
                    continue
                full = Path(root) / fname
                rel  = full.relative_to(args.project_dir)
                zf.write(str(full), str(rel))
                included += 1
                total_bytes += full.stat().st_size

    log.info('  ✓ %s (%d files, %s)',
             out_zip.name, included, _human_size(out_zip.stat().st_size))
    args.python_project_zip = out_zip


def decode_apk(args):
    """Step 5: apktool decode the prebuilt launcher APK."""
    log.info('Step 5/11 -- Decode PySide Launcher APK with apktool')

    decoded_dir = args.workspace / 'decoded'
    if decoded_dir.exists():
        shutil.rmtree(str(decoded_dir))

    run(['java', '-jar', str(args.apktool_jar),
         'd', str(args.launcher_apk),
         '-o', str(decoded_dir),
         '-f',                       # force overwrite
         '--no-debug-info',          # don't pull debug-info we won't change
         ])

    if not decoded_dir.is_dir():
        raise SystemExit('  X apktool d produced no output dir')

    # Quick directory summary for diagnostics
    asset_count = sum(1 for _ in (decoded_dir / 'assets').rglob('*')
                      if _.is_file()) if (decoded_dir / 'assets').is_dir() else 0
    log.info('  ✓ decoded to %s (%d asset files)', decoded_dir, asset_count)

    args.decoded_dir = decoded_dir


def inject_user_project(args):
    """Step 6: drop python_project.zip + tarballs into assets/."""
    log.info('Step 6/11 -- Inject user project + runtime tarballs into assets/')

    assets = args.decoded_dir / 'assets'
    assets.mkdir(parents=True, exist_ok=True)

    # Always replace python_project.zip with the user's bundle
    target = assets / ASSET_PYTHON_PROJECT
    shutil.copy(str(args.python_project_zip), str(target))
    log.info('  ✓ assets/%s   <- user project (%s)',
             ASSET_PYTHON_PROJECT, _human_size(target.stat().st_size))

    # Only inject tarballs if the launcher APK doesn't already ship them.
    # (Some builds of PySideLauncher-debug.apk include them, others don't —
    # we let the user-supplied / downloaded copies be the fallback.)
    for asset_name, src_path in (
        (ASSET_PYTHON_TARBALL, args.python_tarball),
        (ASSET_QT_TARBALL,     args.qt_tarball),
    ):
        target = assets / asset_name
        if target.exists() and target.stat().st_size > MIN_TARBALL_BYTES:
            log.info('  • assets/%s already in APK (%s) — keeping launcher\'s copy',
                     asset_name, _human_size(target.stat().st_size))
        else:
            shutil.copy(str(src_path), str(target))
            log.info('  ✓ assets/%s   <- prebuilt tarball (%s)',
                     asset_name, _human_size(target.stat().st_size))


def rebrand_apk(args):
    """Step 7: optionally update package name + app display name.

    By default the launcher's package is `eu.licentia.necessitas.pyside`
    (or similar).  If --unique-name is supplied, we rewrite the package
    name in AndroidManifest.xml so multiple custom-built apps can coexist
    on the same device.  --app-name updates the display label.
    """
    log.info('Step 7/11 -- Re-package metadata (manifest + strings)')

    if not args.unique_name and not args.app_name:
        log.info('  ✓ no --unique-name or --app-name set; keeping launcher defaults')
        return

    manifest = args.decoded_dir / 'AndroidManifest.xml'
    if not manifest.is_file():
        log.warning('  ! AndroidManifest.xml not found; skipping rebrand')
        return

    txt = manifest.read_text(encoding='utf-8', errors='replace')

    if args.unique_name:
        new_pkg = args.unique_name
        # The manifest has package="..." on the <manifest> root element.
        # Just regex-replace that attribute.  Apktool decodes manifests to
        # XML text, so this is a simple textual edit.
        new_txt, n = re.subn(
            r'package="[^"]+"',
            'package="%s"' % new_pkg,
            txt, count=1)
        if n == 1:
            log.info('  ✓ AndroidManifest package -> %s', new_pkg)
            txt = new_txt
        else:
            log.warning('  ! could not find package="..." in manifest')

    if args.app_name:
        # The display label may be either:
        #   android:label="App Name"     — literal string in manifest
        #   android:label="@string/foo"  — reference to res/values/strings.xml
        # We handle both.
        label_match = re.search(
            r'android:label="(@string/[^"]+|[^"]+)"', txt)
        if label_match:
            label_val = label_match.group(1)
            if label_val.startswith('@string/'):
                # Update the resource entry
                res_name = label_val[len('@string/'):]
                strings_xml = args.decoded_dir / 'res' / 'values' / 'strings.xml'
                if strings_xml.is_file():
                    s = strings_xml.read_text(encoding='utf-8', errors='replace')
                    s2, n = re.subn(
                        r'(<string name="' + re.escape(res_name) + r'"[^>]*>)([^<]*)(</string>)',
                        r'\1' + args.app_name + r'\3',
                        s, count=1)
                    if n == 1:
                        strings_xml.write_text(s2, encoding='utf-8')
                        log.info('  ✓ string resource @string/%s -> "%s"',
                                 res_name, args.app_name)
                    else:
                        log.warning('  ! could not find string resource %s', res_name)
            else:
                # Literal — just replace in manifest
                txt = txt.replace(
                    'android:label="' + label_val + '"',
                    'android:label="' + args.app_name + '"',
                    1)
                log.info('  ✓ android:label literal -> "%s"', args.app_name)

    manifest.write_text(txt, encoding='utf-8')


def rebuild_apk(args):
    """Step 8: re-pack the decoded tree into an unsigned APK."""
    log.info('Step 8/11 -- Rebuild APK with apktool')

    unsigned_apk = args.workspace / 'unsigned.apk'
    if unsigned_apk.exists():
        unsigned_apk.unlink()

    run(['java', '-jar', str(args.apktool_jar),
         'b', str(args.decoded_dir),
         '-o', str(unsigned_apk),
         '--use-aapt2',     # newer/faster packager — required for modern apktool
         ])

    if not unsigned_apk.is_file():
        raise SystemExit('  X apktool b produced no output APK')

    log.info('  ✓ unsigned.apk  : %s', _human_size(unsigned_apk.stat().st_size))
    args.unsigned_apk = unsigned_apk


def zipalign_apk(args):
    """Step 9: align the APK to 4-byte boundaries (Android runtime requirement).

    If zipalign isn't installed we fall back to skipping this step.
    apksigner will warn but the APK still works.
    """
    log.info('Step 9/11 -- Zipalign')

    zipalign = find_tool('zipalign')
    if not zipalign:
        log.warning('  ! zipalign not found on PATH — skipping (APK still works)')
        args.aligned_apk = args.unsigned_apk
        return

    aligned = args.workspace / 'aligned.apk'
    if aligned.exists():
        aligned.unlink()
    run([zipalign, '-p', '-f', '4', str(args.unsigned_apk), str(aligned)])

    log.info('  ✓ aligned.apk   : %s', _human_size(aligned.stat().st_size))
    args.aligned_apk = aligned


def sign_apk(args):
    """Step 10: sign with a debug keystore (created on first run)."""
    log.info('Step 10/11 -- Sign with debug keystore')

    keystore = args.workspace / 'debug.keystore'
    keystore_pass = 'android'
    key_alias = 'androiddebugkey'

    if not keystore.exists():
        log.info('  generating debug keystore')
        keytool = find_tool('keytool')
        if not keytool:
            raise SystemExit('  X keytool not found — need JDK for keystore generation')
        run([keytool, '-genkey', '-v',
             '-keystore', str(keystore),
             '-alias', key_alias,
             '-storepass', keystore_pass,
             '-keypass', keystore_pass,
             '-keyalg', 'RSA',
             '-keysize', '2048',
             '-validity', '10000',
             '-dname', 'CN=Android Debug,O=Android,C=US'])
    else:
        log.info('  ✓ reusing debug keystore: %s', keystore)

    # Prefer apksigner (v2/v3 signing) over jarsigner if available
    apksigner = find_tool('apksigner')
    signed_apk = args.workspace / 'signed.apk'
    if signed_apk.exists():
        signed_apk.unlink()
    shutil.copy(str(args.aligned_apk), str(signed_apk))

    if apksigner:
        log.info('  using apksigner (v2+ signing scheme)')
        run([apksigner, 'sign',
             '--ks', str(keystore),
             '--ks-pass', 'pass:' + keystore_pass,
             '--key-pass', 'pass:' + keystore_pass,
             '--ks-key-alias', key_alias,
             str(signed_apk)])
    else:
        log.info('  using jarsigner (v1 signing scheme — apksigner not on PATH)')
        jarsigner = find_tool('jarsigner')
        if not jarsigner:
            raise SystemExit('  X neither apksigner nor jarsigner found on PATH')
        run([jarsigner, '-verbose',
             '-keystore', str(keystore),
             '-storepass', keystore_pass,
             '-keypass', keystore_pass,
             '-sigalg', 'SHA1withRSA',
             '-digestalg', 'SHA1',
             str(signed_apk), key_alias])

    log.info('  ✓ signed.apk    : %s', _human_size(signed_apk.stat().st_size))
    args.signed_apk = signed_apk


def output_apk(args):
    """Step 11: copy the final APK to --output-path."""
    log.info('Step 11/11 -- Output')

    out = Path(args.output_path).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        out.unlink()
    shutil.copy(str(args.signed_apk), str(out))

    log.info('')
    log.info('===========================================================')
    log.info(' BUILD SUCCEEDED')
    log.info('===========================================================')
    log.info('  APK at:  %s', out)
    log.info('  Size  :  %s', _human_size(out.stat().st_size))
    log.info('  To install on a connected device:')
    log.info('    adb install -r %s', out)
    log.info('===========================================================')


# ------------------------------------------------------------------ main

def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description='Build a PySide 1 / Python 2.6 Android APK by '
                    'injecting your project into the prebuilt PySide '
                    'Launcher APK.')
    p.add_argument('--project-dir', required=True,
                   help='Path to the dir containing main.py (your PySide app).')
    p.add_argument('--output-path', default='./pyside-launcher-app.apk',
                   help='Where to write the final APK.  '
                        'Default: ./pyside-launcher-app.apk')
    p.add_argument('--workspace', default=None,
                   help='Temp workspace dir.  '
                        'Default: a tmp dir under $TMPDIR.')
    p.add_argument('--app-name',
                   help='App display name (shown under the icon).  '
                        'If omitted, keeps the launcher default.')
    p.add_argument('--unique-name',
                   help='Android package id, e.g. com.example.myapp.  '
                        'If omitted, keeps the launcher default '
                        '(meaning only ONE such app can be installed '
                        'on a device at a time).')
    p.add_argument('--verbose', '-v', action='store_true',
                   help='Enable debug logging.')
    return p.parse_args(argv)


def configure_logging(verbose=False):
    level = logging.DEBUG if verbose else logging.INFO
    fmt = '%(asctime)s %(levelname)-5s %(message)s'
    logging.basicConfig(level=level, format=fmt, datefmt='%H:%M:%S')


def main(argv=None):
    args = parse_args(argv)
    configure_logging(args.verbose)

    log.info('===========================================================')
    log.info(' PySide 1 (Qt 4) + Python 2.6 -> Android APK builder')
    log.info('===========================================================')
    log.info('  project       : %s', args.project_dir)
    log.info('  output        : %s', args.output_path)
    log.info('  app name      : %s', args.app_name or '(launcher default)')
    log.info('  unique name   : %s', args.unique_name or '(launcher default)')

    if args.workspace is None:
        args.workspace = tempfile.mkdtemp(prefix='pyside-launcher-builder-')
        log.info('  workspace     : %s (auto-tmp)', args.workspace)

    # Normalize all path-typed args to Path objects so individual steps
    # don't need to defend against str-vs-Path mixups.
    args.workspace   = Path(args.workspace).resolve()
    args.project_dir = Path(args.project_dir).resolve()
    args.output_path = Path(args.output_path).resolve()
    args.workspace.mkdir(parents=True, exist_ok=True)

    try:
        preflight(args)
        workspace_setup(args)
        download_artifacts(args)
        bundle_user_project(args)
        decode_apk(args)
        inject_user_project(args)
        rebrand_apk(args)
        rebuild_apk(args)
        zipalign_apk(args)
        sign_apk(args)
        output_apk(args)
        return 0
    except SystemExit:
        raise
    except Exception:
        log.exception('unhandled exception')
        return 2


if __name__ == '__main__':
    sys.exit(main())
